"""empty message

Revision ID: 178a3d28c247
Revises: 4d3210c61df8
Create Date: 2017-11-16 17:55:19.768659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '178a3d28c247'
down_revision = '4d3210c61df8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=60), nullable=False),
    sa.Column('org_name', sa.String(length=200), nullable=False),
    sa.Column('org_address', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('create_date', sa.Date(), nullable=True),
    sa.Column('modify_date', sa.Date(), nullable=True),
    sa.Column('lock', sa.Boolean(), nullable=True),
    sa.Column('remarks1', sa.String(length=200), nullable=True),
    sa.Column('remarks2', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
